 name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} '
            cd ~/routie &&
            git pull origin main &&
            cd routie-server &&
            ./gradlew build -x test &&
            cd build/libs &&
            pkill -f "java -jar" || true &&
            nohup java -jar routie-server-0.0.1-SNAPSHOT.jar --spring.config.location=file:./application.properties > log.txt 2>&1 &
          '

